CREATE DATABASE School;
USE School;

CREATE TABLE bimester_result(
  id INT AUTO_INCREMENT PRIMARY KEY,
  bimestre VARCHAR(255) NOT NULL,
  disciplina VARCHAR(255) NOT NULL,
  nota INT NOT NULL,
  criadoEm TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizadoEm TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);